source 'https://rubygems.org'

gem 'rails', '3.2.13'

gemspec path: File.expand_path('../../../', __FILE__)

gem 'haml-rails'
gem 'sqlite3'
gem 'puma', github: 'puma/puma'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'bourbon'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'pry'
  gem 'rails-sh'
  gem 'tork'
  gem 'rb-fsevent', '~> 0.9.1'
end

group :test do
  gem 'response_code_matchers'
end

gem 'jquery-rails'
