source 'https://rubygems.org'

gem 'rails', '3.2.11'

gemspec path: File.expand_path('../../../', __FILE__)

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'pry'
  gem 'rails-sh'
end

gem 'jquery-rails'
